version: '2'
services:

  worker-data-importer:
    image: registry.gitlab.com/isteps-sps-lab/human-robot-interaction/better-factory/consensus:0.1.0
    container_name: worker-data-importer
    environment:
        SPREADSHEET: $SPREADSHEET
        MODELS_URL: $MODELS_URL
        MODELS_USER: $BF_USER
        MODELS_PASSWORD: $BF_PASSWORD
        CRONTAB_SCHEDULE: "* */4 * * *"
    volumes:
        - ./fields_map.json:/app/fields_map.json
        - ./service_account.json:/app/service_account.json
    depends_on:
        - models

  models:
    container_name: models
    image: registry.gitlab.com/complemant/integration/data-models:latest
    environment:
      ADMIN_PASSWORD: $BF_PASSWORD
      ADMIN_USERNAME: $BF_USER
      INIT_DATA_DIRECTORY: /var/human/init-data
      KAFKA_REST_PASSWORD: $BF_PASSWORD
      KAFKA_REST_URL: http://middleware:8082
      KAFKA_REST_USER: $BF_USER
      KAFKA_URL: middleware:9092
      KARKA_CLIENT_ID: models
      KARKA_GROUP_ID: models
      MQTT_HOST: sensing-layer_mosquitto
      MQTT_PASSWORD: $BF_PASSWORD
      MQTT_PORT: 1883
      MQTT_USER: $BF_USER
      MYSQL_DB: $MODELS_MYSQL_DATABASE
      MYSQL_HOST: models_db
      MYSQL_PASS: $BF_PASSWORD
      MYSQL_PORT: 3306
      MYSQL_USER: $BF_USER
      SCHEMA_REGISTRY_PASSWORD: $BF_PASSWORD
      SCHEMA_REGISTRY_URL: http://middleware:8081
      SCHEMA_REGISTRY_USER: $BF_USER
      ZOOKEEPER_URL: zookeeper:3181
      spring_profiles_active: kafka
    restart: on-failure
    volumes:
      - ./init-data:/var/human/init-data:rw
    depends_on:
      - models_db

  models_db:
    container_name: models-db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: $MODELS_MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MODELS_MYSQL_DATABASE
      MYSQL_USER: $BF_USER
      MYSQL_PASSWORD: $BF_PASSWORD
    restart: on-failure
    volumes:
      - models_db_data:/var/lib/mysql:rw

networks:
  default:
    name: betterfactory_chri

volumes:
  models_db_data:
